mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_sword>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_shovel>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_pickaxe>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_axe>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_hoe>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_helmet>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_chestplate>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_leggings>);
mods.ResearchStages.addItemStage("bronzeworking", <item:mekanismtools:bronze_boots>);